### DISCUSSION TITLE
SAML2/Shibboleth SSO - Artemis Requests not signed, even though X509 Cert and Key are configured

### DISCUSSION THREAD

**Discussion by solen0id** [ls1intum/Artemis#9579] [Q&A]
Hi Team,

We are currently testing Artemis at HU-Berlin using the docker-compose stack and we're having trouble setting up the SSO via SAML2/Shibboleth. The Artemis Requests appears not to be signed, even though we've configured an X509 certificate and key. Our Shibboleth Admin has configured the Artemis Instance, the config is available for inspection in the HU Berin IdP Metadata XML (https://shib-idp.cms.hu-berlin.de/shibboleth/HU-metadata-g2.xml). 

On the Artemis/SP side, we've enabled the saml2 profile according to the documentation. Both the X509 Cert and Key are available in the `artemis-app` docker container at the provided path (I've checked from within the running container) and should have the proper permissions. Here is our saml2 config:

```yaml
saml2:
    username-pattern: '{urn:oasis:names:tc:SAML:attribute:pairwise-id}'
    first-name-pattern: '{urn:oid:2.5.4.42}'
    last-name-pattern: '{urn:oid:2.5.4.4}'
    email-pattern: '{urn:oid:0.9.2342.19200300.100.1.3}'
    registration-number-pattern: '{urn:oasis:names:tc:SAML:attribute:pairwise-id}'
    lang-key-pattern: 'de'
    value-extraction-patterns:
    identity-providers:
        - metadata: https://shib-idp.cms.hu-berlin.de/shibboleth/HU-metadata-g2.xml
          registration-id: huberlin
          entity-id: https://artemis-gdp.app.informatik.hu-berlin.de/shibboleth
          cert-file: /opt/artemis/data/certs/artemis_cert.crt 
          key-file: /opt/artemis/data/certs/artemis_key.pem 

info.saml2:
    identity-provider-name: HU-Berlin
    button-label: 'HU-Berlin SSO Login'
    password-login-disabled: false
    enable-password: false
```

The cert and key file location and permissions are as follows:

```sh
artemis@f0723c7e6e94:/opt/artemis$ ls -la /opt/artemis/data/certs/
total 16
drwxr-xr-x 2 artemis artemis 4096 Oct 22 09:06 .
drwxr-xr-x 8 artemis artemis 4096 Oct 22 09:06 ..
-rw-r--r-- 1 artemis artemis 2423 Oct 22 09:06 artemis_cert.crt
-rw------- 1 artemis artemis 3272 Oct 22 09:06 artemis_key.pem
```

When performing a test SSO Login, our Shibboleth admin observes that the requests from Artemis are not signed:
`ERROR [org.opensaml.saml.saml2.binding.security.impl.SAML2AuthnRequestsSignedSecurityHandler:77] - SPSSODescriptor for entity ID 'https://artemis-gdp.app.informatik.hu-berlin.de/shibboleth' indicates AuthnRequests must be signed, but inbound message was not signed` 

Is there a configuration setting we are missing, or anything else we're doing incorrectly?

Thanks for your assistance!
Max

**Comment by dfuchss** [comment]
The configuration seems to be fine. Do you see anything in the log? We use a very similar configuration. What is the format for the certificates; I remember that only one format worked. Also: Which version of artemis are you using? We are currently using 7.5.6

**Reply by solen0id** [reply]
We're on Artemis v7.5.5 
Both the X509 Cert and the PKCS#8 Key are in the PEM format to the best of my knowledge.

The Certificate header is `-----BEGIN CERTIFICATE-----`
and the Key header is `-----BEGIN PRIVATE KEY-----`
which indicates to me, we're using the right format, but I might be mistaken here?

**Reply by solen0id** [reply]
The only logs I can find related to the request are from nginx:

```
artemis-nginx  | 141.20.38.117 - - [24/Oct/2024:12:12:28 +0000] "POST /api/public/saml2 HTTP/1.1" 401 0 "https://artemis-gdp.app.informatik.hu-berlin.de/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" "141.20.21.26"
artemis-nginx  | 141.20.38.117 - - [24/Oct/2024:12:12:28 +0000] "GET /saml2/authenticate HTTP/1.1" 302 0 "https://artemis-gdp.app.informatik.hu-berlin.de/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" "141.20.21.26"
artemis-nginx  | 141.20.38.117 - - [24/Oct/2024:12:12:28 +0000] "GET /saml2/authenticate/huberlin HTTP/1.1" 200 1128 "https://artemis-gdp.app.informatik.hu-berlin.de/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" "141.20.21.26"
```

**Reply by dfuchss** [reply]
That seems to be good ..; any logs in the artemis container (maybe activate debug there)

**Reply by solen0id** [reply]
The only additional log line I get from enabling loglevel DEBUG doesn't appear helpful:
`artemis-app  | 2024-10-25T12:18:08.341Z DEBUG 1 --- [Artemis] [cat-handler-198] d.t.c.a.a.c.s.filter.ApiVersionFilter    : Adding Version to Request POST /api/public/saml2`

**Reply by dfuchss** [reply]
I meant during startup. In debug mode many different configuration steps are shown. Also regarding the shibboleth setup

**Reply by dfuchss** [reply]
Primarily, I'm interested in possible outputs from this class :) https://github.com/ls1intum/Artemis/blob/develop/src/main/java/de/tum/cit/aet/artemis/core/config/SAML2Configuration.java

**Reply by solen0id** [reply]
Grepping for "saml2" yields:

```
artemis-app  | 2024-10-25T12:37:52.021Z  INFO 1 --- [Artemis] [           main] de.tum.cit.aet.artemis.ArtemisApp        : The following 9 profiles are active: "artemis", "scheduling", "localci", "localvc", "buildagent", "core", "prod", "docker", "saml2"
artemis-app  | 2024-10-25T12:38:41.933Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-assertion-config.xml'
artemis-app  | 2024-10-25T12:38:41.984Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-assertion-delegation-restriction-config.xml'
artemis-app  | 2024-10-25T12:38:41.992Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-ecp-config.xml'
artemis-app  | 2024-10-25T12:38:42.013Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-metadata-algorithm-config.xml'
artemis-app  | 2024-10-25T12:38:42.021Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-metadata-attr-config.xml'
artemis-app  | 2024-10-25T12:38:42.025Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-metadata-config.xml'
artemis-app  | 2024-10-25T12:38:42.089Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-metadata-idp-discovery-config.xml'
artemis-app  | 2024-10-25T12:38:42.092Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-metadata-query-config.xml'
artemis-app  | 2024-10-25T12:38:42.100Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-metadata-reqinit-config.xml'
artemis-app  | 2024-10-25T12:38:42.103Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-metadata-ui-config.xml'
artemis-app  | 2024-10-25T12:38:42.120Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-metadata-rpi-config.xml'
artemis-app  | 2024-10-25T12:38:42.131Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-protocol-config.xml'
artemis-app  | 2024-10-25T12:38:42.190Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-protocol-thirdparty-config.xml'
artemis-app  | 2024-10-25T12:38:42.193Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-req-attr-config.xml'
artemis-app  | 2024-10-25T12:38:42.198Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-protocol-aslo-config.xml'
artemis-app  | 2024-10-25T12:38:42.200Z DEBUG 1 --- [Artemis] [           main] x.c.AbstractXMLObjectProviderInitializer : Loading XMLObject provider configuration from resource 'saml2-channel-binding-config.xml'
```
and additionally a bunch of marshaller/unmarshaller registrations.

I can't seem to find any loglines related to the SAML2Configuration class you mentioned

**Reply by solen0id** [reply]
My logging settings are:

```yaml
logging:
    level:
        ROOT: DEBUG
        de.tum.cit.aet.artemis: DEBUG
        tech.jhipster: DEBUG
        org.springframework.web.socket.config: DEBUG
        liquibase: DEBUG
        de.jplag.Submission: ERROR
```
